# Compile the last program using a Makefile
# compilation_result is a target, ex1.c is prerequisite, gcc ... is a recipe
compilation_result: ex1.c 
	gcc -o compilation_result ex1.c
clean:
		-rm compilation_result

# To run makefile: make
# To clean (to remove compilation_result): make clean